workflows:
  android-release:
    name: 4R4 Android Release
    max_build_duration: 60
    working_directory: 4R4Android
    environment:
      java: 17

    scripts:
      - name: Gerar gradlew
        script: |
          gradle wrapper --gradle-version 8.7

      - name: Tornar gradlew executável
        script: chmod +x ./gradlew

      - name: Limpar projeto
        script: ./gradlew clean

      - name: Build APK Release
        script: ./gradlew assembleRelease

    artifacts:
      - app/build/outputs/apk/release/*.apk
