workflows:
  android-release:
    name: 4R4 Android Release
    max_build_duration: 60
    working_directory: 4R4Android
    environment:
      java: 17

    scripts:
      - name: Gerar gradlew
        script: |
          gradle wrapper --gradle-version 8.7

      - name: Tornar gradlew executável
        script: chmod +x ./gradlew

      - name: Limpar projeto
        script: ./gradlew clean

      - name: Gerar keystore e assinar APK
        script: |
          keytool -genkey -v \
            -keystore app/4r4-release.keystore \
            -alias 4r4key \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass android123 \
            -keypass android123 \
            -dname "CN=4R4, OU=Dev, O=4R4, L=SP, S=SP, C=BR"

          ./gradlew assembleRelease \
            -Pandroid.injected.signing.store.file=$(pwd)/app/4r4-release.keystore \
            -Pandroid.injected.signing.store.password=android123 \
            -Pandroid.injected.signing.key.alias=4r4key \
            -Pandroid.injected.signing.key.password=android123

    artifacts:
      - app/build/outputs/apk/release/*.apk
