workflows:
  android-release:
    name: 4R4 Android Release
    max_build_duration: 60
    environment:
      java: 17
      vars:
        CARBON_API_KEY: $CARBON_API_KEY

    scripts:
      - name: Set API Key no build.gradle
        script: |
          sed -i "s/SUA_API_KEY_AQUI/$CARBON_API_KEY/" app/build.gradle.kts

      - name: Tornar gradlew executável
        script: chmod +x ./gradlew

      - name: Limpar projeto
        script: ./gradlew clean

      - name: Build APK Release
        script: ./gradlew assembleRelease

    artifacts:
      - app/build/outputs/apk/release/app-release-unsigned.apk

    publishing:
      email:
        recipients:
          - $CM_SUBMITTER_EMAIL
        notify:
          success: true
          failure: true
